"""CQROS Factor Orthogonalization package public API."""

from cqros.factor_orthogonalization.detailed_export import (
    COMBINED_DETAILED_CSV_NAME,
    DETAILED_AUDIT_COLUMNS,
    build_detailed_audit_frame,
    combined_detailed_csv_path,
    detailed_csv_path,
    write_combined_detailed_csv,
    write_detailed_csv,
)
from cqros.factor_orthogonalization.engine import (
    FACTOR_COMBINATION_INPUT_COLUMNS,
    FactorOrthogonalizationEngine,
    LineageContext,
    SimpleFactorOrthogonalizationEngine,
    validate_factor_combination_frame,
)
from cqros.factor_orthogonalization.exceptions import (
    FactorOrthogonalizationError,
    FactorOrthogonalizationException,
)
from cqros.factor_orthogonalization.pipeline import FactorOrthogonalizationPipeline
from cqros.factor_orthogonalization.redundancy import (
    DEFAULT_MAX_COMBINATION_CORRELATION,
    DEFAULT_MIN_CORRELATION_OVERLAP,
    ORTHOGONALIZATION_METHOD,
    ORTHOGONALIZATION_VERSION,
    REASON_ACCEPTED,
    REASON_REDUNDANT,
    OrthogonalizationConfig,
    apply_greedy_combination_filter,
    require_max_combination_correlation,
    require_min_correlation_overlap,
    require_orthogonalization_config,
)
from cqros.factor_orthogonalization.registry import FactorOrthogonalizationRegistry
from cqros.factor_orthogonalization.repository import (
    FactorOrthogonalizationPartitionRef,
    FactorOrthogonalizationRepository,
)
from cqros.factor_orthogonalization.schema import (
    CANONICAL_COLUMN_ORDER,
    COLUMN_DTYPES,
    FACTOR_ORTHOGONALIZATION_COLUMNS,
    FACTOR_ORTHOGONALIZATION_SCHEMA,
    PRIMARY_KEY_COLUMNS,
    REQUIRED_COLUMNS,
    FactorOrthogonalizationStatus,
)
from cqros.factor_orthogonalization.verifier import (
    ERROR_COLUMN_ORDER,
    ERROR_FRAME_EMPTY,
    ERROR_FRAME_TYPE,
    ERROR_LINEAGE_COMBINATION_TYPE,
    ERROR_LINEAGE_DUPLICATE,
    ERROR_LINEAGE_MEMBERSHIP,
    ERROR_LINEAGE_REJECTED_SELECTED,
    ERROR_LINEAGE_THRESHOLD,
    ERROR_LINEAGE_TIMEFRAME,
    ERROR_REQUIRED_COLUMNS,
    ERROR_SCHEMA_MISMATCH,
    FactorOrthogonalizationVerifier,
)

__all__ = [
    "CANONICAL_COLUMN_ORDER",
    "COLUMN_DTYPES",
    "COMBINED_DETAILED_CSV_NAME",
    "DEFAULT_MAX_COMBINATION_CORRELATION",
    "DEFAULT_MIN_CORRELATION_OVERLAP",
    "DETAILED_AUDIT_COLUMNS",
    "ERROR_COLUMN_ORDER",
    "ERROR_FRAME_EMPTY",
    "ERROR_FRAME_TYPE",
    "ERROR_LINEAGE_COMBINATION_TYPE",
    "ERROR_LINEAGE_DUPLICATE",
    "ERROR_LINEAGE_MEMBERSHIP",
    "ERROR_LINEAGE_REJECTED_SELECTED",
    "ERROR_LINEAGE_THRESHOLD",
    "ERROR_LINEAGE_TIMEFRAME",
    "ERROR_REQUIRED_COLUMNS",
    "ERROR_SCHEMA_MISMATCH",
    "FACTOR_COMBINATION_INPUT_COLUMNS",
    "FACTOR_ORTHOGONALIZATION_COLUMNS",
    "FACTOR_ORTHOGONALIZATION_SCHEMA",
    "ORTHOGONALIZATION_METHOD",
    "ORTHOGONALIZATION_VERSION",
    "PRIMARY_KEY_COLUMNS",
    "REASON_ACCEPTED",
    "REASON_REDUNDANT",
    "REQUIRED_COLUMNS",
    "FactorOrthogonalizationEngine",
    "FactorOrthogonalizationError",
    "FactorOrthogonalizationException",
    "FactorOrthogonalizationPartitionRef",
    "FactorOrthogonalizationPipeline",
    "FactorOrthogonalizationRegistry",
    "FactorOrthogonalizationRepository",
    "FactorOrthogonalizationStatus",
    "FactorOrthogonalizationVerifier",
    "LineageContext",
    "OrthogonalizationConfig",
    "SimpleFactorOrthogonalizationEngine",
    "apply_greedy_combination_filter",
    "build_detailed_audit_frame",
    "combined_detailed_csv_path",
    "detailed_csv_path",
    "require_max_combination_correlation",
    "require_min_correlation_overlap",
    "require_orthogonalization_config",
    "validate_factor_combination_frame",
    "write_combined_detailed_csv",
    "write_detailed_csv",
]
