"""CQROS market-data ingestion package public API."""

from cqros.ingestion.chunk_sizing import (
    DEFAULT_CHUNK_SAFETY_FACTOR,
    DOWNLOAD_TIMEFRAMES,
    AdaptiveChunkSizingStrategy,
    ChunkSizingStrategy,
    FixedChunkSizingStrategy,
    effective_kline_count,
    timeframe_duration_ms,
)
from cqros.ingestion.client import (
    DEFAULT_BACKOFF_FACTOR_SECONDS,
    DEFAULT_BINANCE_FUTURES_REST_BASE_URL,
    DEFAULT_BINANCE_FUTURES_TESTNET_REST_BASE_URL,
    DEFAULT_MAX_RETRIES,
    DEFAULT_TIMEOUT_SECONDS,
    BinanceClient,
)
from cqros.ingestion.discovery import SymbolDiscovery
from cqros.ingestion.downloader import (
    DEFAULT_DOWNLOAD_BATCH_SIZE,
    DEFAULT_DOWNLOAD_CHUNK_SIZE_MS,
    DEFAULT_DOWNLOAD_WORKERS,
    DEFAULT_KLINE_REQUEST_LIMIT,
    DownloadPlanner,
    DownloadTask,
    HistoricalDownloader,
)
from cqros.ingestion.funding import (
    DEFAULT_FUNDING_CHUNK_SIZE_MS,
    DEFAULT_FUNDING_INTERVAL_MS,
    DEFAULT_FUNDING_REQUEST_LIMIT,
    DEFAULT_FUNDING_TIMEFRAME,
    FundingDownloader,
    FundingDownloadPlanner,
    FundingDownloadTask,
)
from cqros.ingestion.long_short_ratio import (
    DEFAULT_LONG_SHORT_CHUNK_SAFETY_FACTOR,
    DEFAULT_LONG_SHORT_PERIOD,
    DEFAULT_LONG_SHORT_REQUEST_LIMIT,
    LONG_SHORT_PERIODS,
    LongShortDownloader,
    LongShortDownloadPlanner,
    LongShortDownloadTask,
    LongShortRatioKind,
)
from cqros.ingestion.manifest import (
    DEFAULT_MANIFEST_FILENAME,
    DEFAULT_MANIFEST_SCHEMA_VERSION,
    DatasetManifest,
    ManifestRepository,
    PartitionMetadata,
)
from cqros.ingestion.open_interest import (
    DEFAULT_OPEN_INTEREST_CHUNK_SAFETY_FACTOR,
    DEFAULT_OPEN_INTEREST_PERIOD,
    DEFAULT_OPEN_INTEREST_REQUEST_LIMIT,
    OPEN_INTEREST_PERIODS,
    OpenInterestDownloader,
    OpenInterestDownloadPlanner,
    OpenInterestDownloadTask,
)
from cqros.ingestion.repair import (
    DatasetRepairEngine,
    RepairIssue,
    RepairReport,
    RepairSeverity,
)
from cqros.ingestion.resume import (
    DownloadResult,
    DownloadStatus,
    coerce_latest_timestamp,
    resolve_resume_window,
)
from cqros.ingestion.taker_volume import (
    DEFAULT_TAKER_VOLUME_CHUNK_SAFETY_FACTOR,
    DEFAULT_TAKER_VOLUME_PERIOD,
    DEFAULT_TAKER_VOLUME_REQUEST_LIMIT,
    TAKER_VOLUME_PERIODS,
    TakerVolumeDownloader,
    TakerVolumeDownloadPlanner,
    TakerVolumeDownloadTask,
)
from cqros.ingestion.updater import IncrementalUpdater
from cqros.ingestion.validator import (
    MarketDataValidator,
    ValidationIssue,
    ValidationReport,
    ValidationSeverity,
)

__all__ = [
    "DEFAULT_BACKOFF_FACTOR_SECONDS",
    "DEFAULT_BINANCE_FUTURES_REST_BASE_URL",
    "DEFAULT_BINANCE_FUTURES_TESTNET_REST_BASE_URL",
    "DEFAULT_CHUNK_SAFETY_FACTOR",
    "DEFAULT_DOWNLOAD_BATCH_SIZE",
    "DEFAULT_DOWNLOAD_CHUNK_SIZE_MS",
    "DEFAULT_DOWNLOAD_WORKERS",
    "DEFAULT_FUNDING_CHUNK_SIZE_MS",
    "DEFAULT_FUNDING_INTERVAL_MS",
    "DEFAULT_FUNDING_REQUEST_LIMIT",
    "DEFAULT_FUNDING_TIMEFRAME",
    "DEFAULT_KLINE_REQUEST_LIMIT",
    "DEFAULT_LONG_SHORT_CHUNK_SAFETY_FACTOR",
    "DEFAULT_LONG_SHORT_PERIOD",
    "DEFAULT_LONG_SHORT_REQUEST_LIMIT",
    "DEFAULT_MANIFEST_FILENAME",
    "DEFAULT_MANIFEST_SCHEMA_VERSION",
    "DEFAULT_MAX_RETRIES",
    "DEFAULT_OPEN_INTEREST_CHUNK_SAFETY_FACTOR",
    "DEFAULT_OPEN_INTEREST_PERIOD",
    "DEFAULT_OPEN_INTEREST_REQUEST_LIMIT",
    "DEFAULT_TAKER_VOLUME_CHUNK_SAFETY_FACTOR",
    "DEFAULT_TAKER_VOLUME_PERIOD",
    "DEFAULT_TAKER_VOLUME_REQUEST_LIMIT",
    "DEFAULT_TIMEOUT_SECONDS",
    "DOWNLOAD_TIMEFRAMES",
    "LONG_SHORT_PERIODS",
    "OPEN_INTEREST_PERIODS",
    "TAKER_VOLUME_PERIODS",
    "AdaptiveChunkSizingStrategy",
    "BinanceClient",
    "ChunkSizingStrategy",
    "DatasetManifest",
    "DatasetRepairEngine",
    "DownloadPlanner",
    "DownloadResult",
    "DownloadStatus",
    "DownloadTask",
    "FixedChunkSizingStrategy",
    "FundingDownloadPlanner",
    "FundingDownloadTask",
    "FundingDownloader",
    "HistoricalDownloader",
    "IncrementalUpdater",
    "LongShortDownloadPlanner",
    "LongShortDownloadTask",
    "LongShortDownloader",
    "LongShortRatioKind",
    "ManifestRepository",
    "MarketDataValidator",
    "OpenInterestDownloadPlanner",
    "OpenInterestDownloadTask",
    "OpenInterestDownloader",
    "PartitionMetadata",
    "RepairIssue",
    "RepairReport",
    "RepairSeverity",
    "SymbolDiscovery",
    "TakerVolumeDownloadPlanner",
    "TakerVolumeDownloadTask",
    "TakerVolumeDownloader",
    "ValidationIssue",
    "ValidationReport",
    "ValidationSeverity",
    "coerce_latest_timestamp",
    "effective_kline_count",
    "resolve_resume_window",
    "timeframe_duration_ms",
]
